export {default as Navbar} from './Navbar'
export {default as Hero} from './Hero'
export {default as About} from './About'
export {default as PricingProduct} from './PricingProduct'
export {default as Footer} from './Footer'